[build]
rustflags = [
    "-C", "target-cpu=x86-64-v3",
    "-C", "link-arg=-Wl,-z,now",
    "-Z", "tls-model=initial-exec",
    "-C", "force-unwind-tables=no",
    "-C", "llvm-args=-align-all-functions=5",
    "-C", "llvm-args=-x86-pad-for-align=false",
    "-C", "llvm-args=--inline-threshold=275",
    "-C", "code-model=small"
]
